export const APP_NAME = import.meta.env.VITE_DAPP_NAME ||'DotPassport Sandbox';
export const API_URL = import.meta.env.VITE_API_URL ||'http://localhost:4000/api/v1'; export const RATE_LIMITS = { FREE: { hourly: 100, daily: 1000, monthly: 10000, }, PRO: { hourly: 1000, daily: 10000, monthly: 100000, }, ENTERPRISE: { hourly: 10000, daily: 100000, monthly: 1000000, },
}; export const SUGGESTED_ADDRESSES = [ { name:"The White Rabbit", address:"13pgGkebYEYGLhA7eR6sBM1boEvq86V9adonjswtYe1iDK2K", }, { name:"Clara", address:"12aoZXwbUzsv3z5HF5HCrtEwBJYCeKne6rYsxFEKDZ86Wdv8", }, { name:"Serban Iorga", address:"14oHMAJ5btnDCusHrTWraw1wTsLJwZeqPDLxusm1R1Zh3Vxa", }, { name:"Shawn Tabrizi", address:"12hAtDZJGt4of3m2GqZcUCVAjZPALfvPwvtUTFZPQUbdX1Ud", }, { name:"Bastian Köcher", address:"13fvj4bNfrTo8oW6U8525soRp6vhjAFLum6XBdtqq9yP22E7", }, { name:"George Pisaltu", address:"128pmEUBSGjGeXZXNaAmomAJgVn77L74YT7Zdjd3fP63HWNP", }, { name:"Alexander Theißen", address:"15db5ksZgmhWE9U8MDq4wLKUdFivLVBybztWV8nmaJvv3NU1", }, { name:"Valletech", address:"15yhxUC89ULF3WxvH2P6r4ktWRPhF7r7LtXMaGGADoyVxs2B", },
]; // Keep backward compatibility
export const DEFAULT_ADDRESSES = { ALICE: SUGGESTED_ADDRESSES[0].address, BOB: SUGGESTED_ADDRESSES[1].address, CHARLIE: SUGGESTED_ADDRESSES[2].address,
}; export const SDK_METHODS = [ { name:'getProfile', description:'Get user profile by Polkadot address', params: ['address: string'], example:`client.getProfile('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')`, }, { name:'getScores', description:'Get all reputation scores for a user', params: ['address: string'], example:`client.getScores('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')`, }, { name:'getCategoryScore', description:'Get specific category score for a user', params: ['address: string','category: string'], example:`client.getCategoryScore('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY','Developer')`, }, { name:'getBadges', description:'Get all badges earned by a user', params: ['address: string'], example:`client.getBadges('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')`, }, { name:'getBadge', description:'Get specific badge details for a user', params: ['address: string','badgeName: string'], example:`client.getBadge('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY','Early Adopter')`, }, { name:'getBadgeDefinitions', description:'Get all available badge definitions', params: [], example:`client.getBadgeDefinitions()`, }, { name:'getCategoryDefinitions', description:'Get all category definitions', params: [], example:`client.getCategoryDefinitions()`, },
]; export const WIDGET_TYPES = [ { name:'ReputationWidget', description:'Display overall reputation score', props: ['address','theme?','apiKey'], }, { name:'BadgeWidget', description:'Display earned badges', props: ['address','theme?','apiKey'], }, { name:'ProfileWidget', description:'Display full user profile', props: ['address','theme?','apiKey'], }, { name:'CategoryWidget', description:'Display category scores', props: ['address','category','theme?','apiKey'], },
]; export const THEME_OPTIONS = { light: { background:'#FFFFFF', text:'#1A1A1A', primary:'#E6007A', secondary:'#552BBF', }, dark: { background:'#1A1A1A', text:'#FFFFFF', primary:'#E6007A', secondary:'#552BBF', }, custom: { background:'#F5F5F5', text:'#333333', primary:'#FF6B9D', secondary:'#7B5EA7', },
};
